project:
  type: website
  output-dir: docs

website:
  title: "Samuel Nitkin"
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: CV
        href: cv.qmd
      - text: Research
        href: research.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    anchor-sections: false
    link-external-newwindow: true
